/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/todos": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					completed?: string;
					sortBy?: "createdAt";
					order?: "asc" | "desc";
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description TODOリストを返す */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Todo"][];
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CreateTodo"];
				};
			};
			responses: {
				/** @description 作成されたTODOを返す */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Todo"];
					};
				};
				/** @description バリデーションエラー */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/todos/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description TODOを返す */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Todo"];
					};
				};
				/** @description TODOが見つからない */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["UpdateTodo"];
				};
			};
			responses: {
				/** @description 更新されたTODOを返す */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Todo"];
					};
				};
				/** @description TODOが見つからない */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description TODOを削除した */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description TODOが見つからない */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Todo: {
			/**
			 * Format: uuid
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string;
			/** @example 買い物に行く */
			title: string;
			/** @example 牛乳とパンを買う */
			description?: string;
			/** @example false */
			completed: boolean;
			/**
			 * Format: date-time
			 * @example 2024-01-01T00:00:00Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2024-01-01T00:00:00Z
			 */
			updatedAt: string;
		};
		CreateTodo: {
			title: string;
			description?: string;
		};
		UpdateTodo: {
			title?: string;
			description?: string;
			completed?: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
